function [modelFile, model] = Build_TrackShift_F1_HEV_Model(varargin)
% Build_TrackShift_F1_HEV_Model
% Builds a connected native Simulink model for the TrackShift F1-style
% 2026 hybrid-electric power unit demonstrator.
%
% The generated SLX is signal-level rather than Simscape Electrical because
% Simscape Electrical is not installed on the build host. It exposes the
% mechanical/electrical component boundaries explicitly and runs with
% Simulink + Stateflow/MATLAB Function blocks in MATLAB R2025a or Online.
%
% Usage:
%   [file, model] = Build_TrackShift_F1_HEV_Model;
%   [file, model] = Build_TrackShift_F1_HEV_Model('openAfterBuild',true);
%
% The generated model runs two parallel branches from the same telemetry:
%   1) OVERTAKE MODE: handover AI policy may deploy MGU-K power.
%   2) NO OVERTAKE MODE: deployment is disabled; regeneration remains
%      available when braking is permitted.

opts = parseOptions(varargin{:});
mdl = opts.modelName;
modelFile = fullfile(pwd, [mdl '.slx']);

if bdIsLoaded(mdl)
    close_system(mdl, 0);
end
if exist(modelFile, 'file')
    if ~opts.overwrite
        error('Model file already exists: %s', modelFile);
    end
    delete(modelFile);
end

load_system('simulink');
new_system(mdl);
set_param(mdl, 'Location', [40 40 1600 900]);
set_param(mdl, 'Solver', 'FixedStepDiscrete', ...
    'FixedStep', '0.25', 'StopTime', num2str(opts.stopTime_s), ...
    'SaveOutput', 'on', 'OutputSaveName', 'yout', ...
    'SignalLogging', 'on', 'SignalLoggingName', 'logsout', ...
    'ReturnWorkspaceOutputs', 'on');

[t, speed_kph, gap_s, throttle, brake, trackPos_m, gradient_rad] = ...
    makeScenarioSignals(opts.stopTime_s);
ws = get_param(mdl, 'ModelWorkspace');
ws.DataSource = 'Model File';
ws.assignin('TS_SPEED_KPH', [t speed_kph]);
ws.assignin('TS_GAP_S', [t gap_s]);
ws.assignin('TS_THROTTLE', [t throttle]);
ws.assignin('TS_BRAKE', [t brake]);
ws.assignin('TS_TRACK_POS_M', [t trackPos_m]);
ws.assignin('TS_GRADIENT_RAD', [t gradient_rad]);
ws.assignin('TS_ENGINE_CAPACITY_L', 1.6);
ws.assignin('TS_SAMPLE_TIME_S', 0.25);
ws.assignin('TS_HANDOVER_SOURCE', ...
    'handover.rar / handover/export/models (production logistic models)');

buildScenarioInputs([mdl '/Scenario Inputs']);
buildHEVMode([mdl '/OVERTAKE MODE - AI DEPLOY'], true);
buildHEVMode([mdl '/NO OVERTAKE MODE - HOLD + REGEN'], false);
connectScenarioBranches(mdl);
buildTopLevelDashboard(mdl);
buildTopLevelLogging(mdl);

save_system(mdl, modelFile);

% Compile and execute once so the generated model is delivered tested.
set_param(mdl, 'SimulationCommand', 'update');
sim(mdl, 'ReturnWorkspaceOutputs', 'on');
save_system(mdl, modelFile);

model = struct();
model.name = mdl;
model.file = modelFile;
model.sampleTime_s = 0.25;
model.stopTime_s = opts.stopTime_s;
model.modeBranches = ["OVERTAKE MODE - AI DEPLOY"; ...
    "NO OVERTAKE MODE - HOLD + REGEN"];
model.components = ["Scenario Inputs"; "AI Overtake Policy + Rule Gate"; ...
    "Regenerative Braking"; "ICE: 1.6 L V6 Turbo + Fuel Flow"; ...
    "Power Command Governor"; "Inverter + DC Link"; ...
    "MGU-K Electric Machine"; "Energy Store Battery"; ...
    "Turbocharger + Intercooler"; "Fuel System + Injectors"; ...
    "BMS + HV Safety + Thermal Management"; ...
    "Brake-by-Wire + Friction Brakes"; ...
    "8-Speed Gearbox + Differential"; "Aerodynamics + Tyres"; ...
    "Longitudinal Vehicle Dynamics"; "Live Displays and Scopes"];
model.aiSource = 'Embedded handover zone_pass_model, rival_cover_model, deployment_policy, lap_trial_models';
model.validation = 'Model update and fixed-step simulation completed in MATLAB R2025a';

if opts.openAfterBuild
    open_system(mdl);
end
end

function opts = parseOptions(varargin)
p = inputParser;
addParameter(p, 'modelName', 'TrackShift_F1_HEV', @(x) ischar(x) || isstring(x));
addParameter(p, 'stopTime_s', 90, @(x) isnumeric(x) && isscalar(x) && x > 1);
addParameter(p, 'overwrite', true, @(x) islogical(x) || (isnumeric(x) && isscalar(x)));
addParameter(p, 'openAfterBuild', false, @(x) islogical(x) || (isnumeric(x) && isscalar(x)));
parse(p, varargin{:});
opts = p.Results;
opts.modelName = char(opts.modelName);
opts.overwrite = logical(opts.overwrite);
opts.openAfterBuild = logical(opts.openAfterBuild);
end

function [t, speed_kph, gap_s, throttle, brake, trackPos_m, gradient_rad] = ...
    makeScenarioSignals(stopTime_s)
dt = 0.25;
t = (0:dt:stopTime_s)';
speed_kph = 220 + 34*sin(2*pi*t/38) + 16*sin(2*pi*t/17);
speed_kph = speed_kph - 42*exp(-((t-18)/2.4).^2);
speed_kph = speed_kph - 38*exp(-((t-48)/2.8).^2);
speed_kph = speed_kph - 45*exp(-((t-75)/2.7).^2);
speed_kph = min(max(speed_kph, 80), 330);
speed_mps = speed_kph/3.6;
trackPos_m = cumtrapz(t, speed_mps);
lapLength_m = trackPos_m(end);

gap_s = 1.35*ones(size(t));
detectionFractions = [0.19 0.50 0.78];
for i = 1:numel(detectionFractions)
    d0 = detectionFractions(i)*lapLength_m;
    width = 0.10*lapLength_m;
    closeFactor = 1.05;
    if i == 2
        closeFactor = 0.70;
    end
    gap_s = gap_s - closeFactor*exp(-0.5*((trackPos_m-d0)/width).^2);
end
gap_s = min(max(gap_s + 0.03*sin(2*pi*t/9), 0.35), 2.0);

accel = [0; diff(speed_mps)/dt];
throttle = 0.58 + 0.18*sin(2*pi*t/31) + 0.12*(accel > 0);
throttle = min(max(throttle, 0.10), 0.98);
brake = min(max(-accel/7.5, 0), 1);
activationFractions = [0.23 0.54 0.82];
brakingZone = false(size(t));
for i = 1:numel(activationFractions)
    d0 = activationFractions(i)*lapLength_m - 0.08*lapLength_m;
    d1 = activationFractions(i)*lapLength_m + 0.04*lapLength_m;
    brakingZone = brakingZone | (trackPos_m >= d0 & trackPos_m <= d1);
end
brake = max(brake, 0.75*double(brakingZone));
gradient_rad = deg2rad(0.7)*sin(2*pi*trackPos_m/lapLength_m);
end

function buildScenarioInputs(path)
if exist(path, 'file')
    delete_block(path);
end
add_block('simulink/Ports & Subsystems/Subsystem', path, ...
    'Position', [30 130 240 640]);
deleteDefaultContents(path);
signals = { ...
    'Speed_kph', 'TS_SPEED_KPH'; ...
    'Gap_s', 'TS_GAP_S'; ...
    'Throttle', 'TS_THROTTLE'; ...
    'Brake', 'TS_BRAKE'; ...
    'TrackPos_m', 'TS_TRACK_POS_M'; ...
    'Gradient_rad', 'TS_GRADIENT_RAD'};
for i = 1:size(signals, 1)
    y = 30 + (i-1)*75;
    b = [path '/' signals{i,1} '_source'];
    add_block('simulink/Sources/From Workspace', b, ...
        'VariableName', signals{i,2}, 'Position', [25 y 145 y+35]);
    out = [path '/' signals{i,1}];
    add_block('simulink/Ports & Subsystems/Out1', out, ...
        'Port', num2str(i), 'Position', [175 y+7 205 y+23]);
    add_line(path, [signals{i,1} '_source/1'], [signals{i,1} '/1']);
end
set_param(path, 'BackgroundColor', '[0.88 0.93 0.98]');
end

function buildHEVMode(path, overtakeEnabled)
if exist(path, 'file')
    delete_block(path);
end
modePosition = [285 80 800 350];
if ~overtakeEnabled
    modePosition = [285 390 800 660];
end
add_block('simulink/Ports & Subsystems/Subsystem', path, ...
    'Position', modePosition);
deleteDefaultContents(path);

inNames = {'Speed_kph','Gap_s','Throttle','Brake','TrackPos_m','Gradient_rad'};
for i = 1:numel(inNames)
    y = 35 + (i-1)*42;
    add_block('simulink/Ports & Subsystems/In1', [path '/' inNames{i}], ...
        'Port', num2str(i), 'Position', [20 y 50 y+18]);
end

modeValue = '0';
if overtakeEnabled
    modeValue = '1';
end
add_block('simulink/Sources/Constant', [path '/OvertakeEnabled'], ...
    'Value', modeValue, 'Position', [25 300 85 330]);

addMatlabFunction([path '/AI Overtake Policy + Rule Gate'], ...
    [150 40 350 250], aiScript());
addMatlabFunction([path '/Regenerative Braking'], ...
    [150 275 300 335], regenScript());
addMatlabFunction([path '/ICE: 1.6 L V6 Turbo + Fuel Flow'], ...
    [390 40 580 150], iceScript());
addMatlabFunction([path '/Turbocharger + Intercooler'], ...
    [390 335 580 405], turboScript());
addMatlabFunction([path '/Fuel System + Injectors'], ...
    [620 335 790 405], fuelScript());
addMatlabFunction([path '/Power Command Governor'], ...
    [390 185 580 300], governorScript());
addMatlabFunction([path '/Inverter + DC Link'], ...
    [620 40 760 90], inverterScript());
addMatlabFunction([path '/MGU-K Electric Machine'], ...
    [620 120 790 210], mguScript());
addMatlabFunction([path '/Energy Store Battery'], ...
    [820 40 1000 190], batteryScript());
addMatlabFunction([path '/BMS + HV Safety + Thermal Management'], ...
    [1020 35 1180 145], bmsScript());
add_block('simulink/Discrete/Unit Delay', [path '/Battery Energy Memory'], ...
    'InitialCondition', '11.52', 'SampleTime', '0.25', ...
    'Position', [610 230 760 270]);
addMatlabFunction([path '/8-Speed Gearbox + Differential'], ...
    [820 230 1000 310], gearboxScript());
addMatlabFunction([path '/Aerodynamics + Tyres'], ...
    [1020 220 1170 290], aeroScript());
addMatlabFunction([path '/Brake-by-Wire + Friction Brakes'], ...
    [1020 335 1240 405], brakeScript());
addMatlabFunction([path '/Longitudinal Vehicle Dynamics'], ...
    [1200 95 1390 230], vehicleScript());

outNames = {'Speed_actual_kph','Rule_gate','AI_recommendation', ...
    'P_success','P_no_deploy','P_rival_cover','Expected_gain', ...
    'P_request_kW','P_final_kW','Decision_mode','Engine_power_kW', ...
    'Engine_torque_Nm','Fuel_flow_MJph','MGUK_electrical_kW', ...
    'MGUK_mechanical_kW','MGUK_torque_Nm','Battery_energy_MJ', ...
    'Battery_SOC_percent','Battery_voltage_V','Battery_current_A', ...
    'Battery_power_kW','Distance_m','Acceleration_m_s2','Gear', ...
    'Governor_clip','Governor_reason','Regen_available_kW','Wheel_power_kW'};
for i = 1:numel(outNames)
    y = 20 + (i-1)*27;
    add_block('simulink/Ports & Subsystems/Out1', [path '/' outNames{i}], ...
        'Port', num2str(i), 'Position', [1450 y 1480 y+16]);
end

for i = 1:5
    add_line(path, [inNames{i} '/1'], ...
        ['AI Overtake Policy + Rule Gate/' num2str(i)], 'autorouting', 'on');
end
add_line(path, 'OvertakeEnabled/1', 'AI Overtake Policy + Rule Gate/6', ...
    'autorouting', 'on');
add_line(path, 'Brake/1', 'Regenerative Braking/1', 'autorouting', 'on');
add_line(path, 'Speed_kph/1', 'Regenerative Braking/2', 'autorouting', 'on');
add_line(path, 'Regenerative Braking/1', ...
    'AI Overtake Policy + Rule Gate/7', 'autorouting', 'on');

add_line(path, 'Speed_kph/1', 'ICE: 1.6 L V6 Turbo + Fuel Flow/1', 'autorouting','on');
add_line(path, 'Throttle/1', 'ICE: 1.6 L V6 Turbo + Fuel Flow/2', 'autorouting','on');
add_line(path, 'Brake/1', 'ICE: 1.6 L V6 Turbo + Fuel Flow/3', 'autorouting','on');
add_line(path, 'Speed_kph/1', 'Turbocharger + Intercooler/1', 'autorouting','on');
add_line(path, 'Throttle/1', 'Turbocharger + Intercooler/2', 'autorouting','on');
add_line(path, 'Turbocharger + Intercooler/1', ...
    'ICE: 1.6 L V6 Turbo + Fuel Flow/4', 'autorouting','on');
add_line(path, 'ICE: 1.6 L V6 Turbo + Fuel Flow/3', ...
    'Fuel System + Injectors/1', 'autorouting','on');
add_line(path, 'Throttle/1', 'Fuel System + Injectors/2', 'autorouting','on');
add_line(path, 'AI Overtake Policy + Rule Gate/7', 'Power Command Governor/1', 'autorouting','on');
add_line(path, 'AI Overtake Policy + Rule Gate/1', 'Power Command Governor/2', 'autorouting','on');
add_line(path, 'Speed_kph/1', 'Power Command Governor/3', 'autorouting','on');
add_line(path, 'Brake/1', 'Power Command Governor/4', 'autorouting','on');
add_line(path, 'Battery Energy Memory/1', 'Power Command Governor/5', 'autorouting','on');
add_line(path, 'Power Command Governor/1', 'Inverter + DC Link/1', 'autorouting','on');
add_line(path, 'Power Command Governor/1', 'MGU-K Electric Machine/1', 'autorouting','on');
add_line(path, 'Speed_kph/1', 'MGU-K Electric Machine/2', 'autorouting','on');
add_line(path, 'Inverter + DC Link/1', ...
    'BMS + HV Safety + Thermal Management/1', 'autorouting','on');
add_line(path, 'Battery Energy Memory/1', 'Energy Store Battery/2', 'autorouting','on');
add_line(path, 'Battery Energy Memory/1', ...
    'BMS + HV Safety + Thermal Management/2', 'autorouting','on');
add_line(path, 'BMS + HV Safety + Thermal Management/1', ...
    'Energy Store Battery/1', 'autorouting','on');
add_line(path, 'Energy Store Battery/1', 'Battery Energy Memory/1', 'autorouting','on');
add_line(path, 'ICE: 1.6 L V6 Turbo + Fuel Flow/1', ...
    '8-Speed Gearbox + Differential/1', 'autorouting','on');
add_line(path, 'MGU-K Electric Machine/1', ...
    '8-Speed Gearbox + Differential/2', 'autorouting','on');
add_line(path, 'Speed_kph/1', '8-Speed Gearbox + Differential/3', 'autorouting','on');
add_line(path, '8-Speed Gearbox + Differential/1', 'Aerodynamics + Tyres/1', 'autorouting','on');
add_line(path, 'Speed_kph/1', 'Aerodynamics + Tyres/2', 'autorouting','on');
add_line(path, 'Aerodynamics + Tyres/1', 'Longitudinal Vehicle Dynamics/1', 'autorouting','on');
add_line(path, 'Speed_kph/1', 'Longitudinal Vehicle Dynamics/2', 'autorouting','on');
add_line(path, 'Brake/1', 'Brake-by-Wire + Friction Brakes/1', 'autorouting','on');
add_line(path, 'Speed_kph/1', 'Brake-by-Wire + Friction Brakes/2', 'autorouting','on');
add_line(path, 'Brake-by-Wire + Friction Brakes/1', ...
    'Longitudinal Vehicle Dynamics/3', 'autorouting','on');
add_line(path, 'Gradient_rad/1', 'Longitudinal Vehicle Dynamics/4', 'autorouting','on');
add_line(path, 'TrackPos_m/1', 'Longitudinal Vehicle Dynamics/5', 'autorouting','on');

map = { ...
    'Longitudinal Vehicle Dynamics/1',1; 'AI Overtake Policy + Rule Gate/1',2; ...
    'AI Overtake Policy + Rule Gate/2',3; 'AI Overtake Policy + Rule Gate/3',4; ...
    'AI Overtake Policy + Rule Gate/4',5; 'AI Overtake Policy + Rule Gate/5',6; ...
    'AI Overtake Policy + Rule Gate/6',7; 'AI Overtake Policy + Rule Gate/7',8; ...
    'Power Command Governor/1',9; 'AI Overtake Policy + Rule Gate/8',10; ...
    'ICE: 1.6 L V6 Turbo + Fuel Flow/1',11; 'ICE: 1.6 L V6 Turbo + Fuel Flow/2',12; ...
    'ICE: 1.6 L V6 Turbo + Fuel Flow/3',13; 'Power Command Governor/1',14; ...
    'MGU-K Electric Machine/1',15; 'MGU-K Electric Machine/2',16; ...
    'Energy Store Battery/1',17; 'Energy Store Battery/2',18; ...
    'Energy Store Battery/3',19; 'Energy Store Battery/4',20; ...
    'Energy Store Battery/5',21; 'Longitudinal Vehicle Dynamics/3',22; ...
    'Longitudinal Vehicle Dynamics/2',23; '8-Speed Gearbox + Differential/2',24; ...
    'Power Command Governor/2',25; 'Power Command Governor/3',26; ...
    'Regenerative Braking/1',27; '8-Speed Gearbox + Differential/1',28};
for i = 1:size(map,1)
    add_line(path, map{i,1}, [outNames{map{i,2}} '/1'], 'autorouting','on');
end

set_param(path, 'BackgroundColor', '[0.95 0.95 0.90]');
end

function connectScenarioBranches(mdl)
modePaths = {'OVERTAKE MODE - AI DEPLOY', 'NO OVERTAKE MODE - HOLD + REGEN'};
for i = 1:6
    for j = 1:numel(modePaths)
        add_line(mdl, ['Scenario Inputs/' num2str(i)], ...
            [modePaths{j} '/' num2str(i)], 'autorouting', 'on');
    end
end
end

function buildTopLevelDashboard(mdl)
% Direct Display blocks keep the key values readable on the top-level page.
add_block('simulink/Sources/Constant', [mdl '/Engine capacity 1.6 L'], ...
    'Value', 'TS_ENGINE_CAPACITY_L', 'Position', [835 35 920 65]);
add_block('simulink/Sinks/Display', [mdl '/ENGINE CAPACITY (L)'], ...
    'Position', [945 28 1085 72]);
add_line(mdl, 'Engine capacity 1.6 L/1', 'ENGINE CAPACITY (L)/1', 'autorouting','on');

labels = { ...
    'AI P(pass)', 4, 90, 4; 'AI expected gain', 7, 150, 7; ...
    'AI final MGU-K kW', 9, 210, 9; 'AI decision mode', 10, 270, 10; ...
    'AI engine kW', 11, 330, 11; 'AI engine torque Nm', 12, 390, 12; ...
    'AI battery energy MJ', 17, 450, 17; 'AI battery SOC %', 18, 510, 18; ...
    'AI battery voltage V', 19, 570, 19; 'AI battery current A', 20, 630, 20; ...
    'AI battery power kW', 21, 690, 21; 'AI vehicle speed kph', 1, 750, 1; ...
    'NO-OT P(pass)', 4, 90, 4; 'NO-OT expected gain', 7, 150, 7; ...
    'NO-OT MGU-K kW', 9, 210, 9; 'NO-OT decision mode', 10, 270, 10; ...
    'NO-OT engine kW', 11, 330, 11; 'NO-OT battery energy MJ', 17, 390, 17; ...
    'NO-OT battery SOC %', 18, 450, 18; 'NO-OT battery power kW', 21, 510, 21};
for i = 1:size(labels,1)
    name = labels{i,1};
    port = labels{i,2};
    y = labels{i,3};
    if i <= 12
        x = 835;
        src = ['OVERTAKE MODE - AI DEPLOY/' num2str(port)];
    else
        x = 1110;
        src = ['NO OVERTAKE MODE - HOLD + REGEN/' num2str(port)];
    end
    block = [mdl '/' name];
    add_block('simulink/Sinks/Display', block, 'Position', [x y x+180 y+38]);
    add_line(mdl, src, [name '/1'], 'autorouting','on');
end

add_block('simulink/Signal Routing/Mux', [mdl '/MUX Battery Energy'], ...
    'Inputs', '2', 'Position', [820 820 850 880]);
add_block('simulink/Sinks/Scope', [mdl '/SCOPE Battery Energy AI vs No-OT'], ...
    'Position', [900 805 1080 895]);
add_line(mdl, 'OVERTAKE MODE - AI DEPLOY/17', 'MUX Battery Energy/1', 'autorouting','on');
add_line(mdl, 'NO OVERTAKE MODE - HOLD + REGEN/17', 'MUX Battery Energy/2', 'autorouting','on');
add_line(mdl, 'MUX Battery Energy/1', 'SCOPE Battery Energy AI vs No-OT/1', 'autorouting','on');

add_block('simulink/Signal Routing/Mux', [mdl '/MUX MGU-K Power'], ...
    'Inputs', '2', 'Position', [1120 820 1150 880]);
add_block('simulink/Sinks/Scope', [mdl '/SCOPE MGU-K Power AI vs No-OT'], ...
    'Position', [1200 805 1380 895]);
add_line(mdl, 'OVERTAKE MODE - AI DEPLOY/9', 'MUX MGU-K Power/1', 'autorouting','on');
add_line(mdl, 'NO OVERTAKE MODE - HOLD + REGEN/9', 'MUX MGU-K Power/2', 'autorouting','on');
add_line(mdl, 'MUX MGU-K Power/1', 'SCOPE MGU-K Power AI vs No-OT/1', 'autorouting','on');

try
    Simulink.Annotation(mdl, ['TrackShift F1 2026 HEV | two-mode comparison | ' ...
        '1.6 L V6 turbo | MGU-K only (MGU-H omitted) | ' ...
        'positive MGU-K = deploy, negative = regenerate']);
catch
    % Annotation availability is not required for the model to run.
end
end

function buildTopLevelLogging(mdl)
logging = { ...
    'AI_Battery_Energy_MJ', 'OVERTAKE MODE - AI DEPLOY/17'; ...
    'AI_Battery_SOC_percent', 'OVERTAKE MODE - AI DEPLOY/18'; ...
    'AI_MGUK_Power_kW', 'OVERTAKE MODE - AI DEPLOY/9'; ...
    'AI_Engine_Power_kW', 'OVERTAKE MODE - AI DEPLOY/11'; ...
    'NoOvertake_Battery_Energy_MJ', 'NO OVERTAKE MODE - HOLD + REGEN/17'; ...
    'NoOvertake_Battery_SOC_percent', 'NO OVERTAKE MODE - HOLD + REGEN/18'; ...
    'NoOvertake_MGUK_Power_kW', 'NO OVERTAKE MODE - HOLD + REGEN/9'};
for i = 1:size(logging,1)
    x = 150 + mod(i-1, 4)*180;
    y = 920 + floor((i-1)/4)*45;
    block = [mdl '/ToWs_' logging{i,1}];
    add_block('simulink/Sinks/To Workspace', block, ...
        'VariableName', logging{i,1}, 'SaveFormat', 'Structure With Time', ...
        'Position', [x y x+145 y+30]);
    add_line(mdl, logging{i,2}, ['ToWs_' logging{i,1} '/1'], 'autorouting','on');
end
end

function deleteDefaultContents(path)
blocks = find_system(path, 'SearchDepth', 1, 'Type', 'Block');
for i = 1:numel(blocks)
    if ~strcmp(blocks{i}, path)
        delete_block(blocks{i});
    end
end
end

function addMatlabFunction(path, position, script)
add_block('simulink/User-Defined Functions/MATLAB Function', path, ...
    'Position', position);
chart = find(sfroot, '-isa', 'Stateflow.EMChart', 'Path', path);
chart.Script = script;
end

function script = aiScript()
script = [ ...
'function [ruleGate,aiRecommendation,pSuccess,pNoDeploy,pCover,expectedGain,pRequest,decisionMode] = f(speed_kph,gap_s,throttle,brake,trackPos_m,modeEnable,regenAvail)' newline ...
'% Production coefficients embedded from handover.rar.' newline ...
'zone = [-0.7075777832923592;-6.026485573777835;-0.04895038433595806;-0.13455035383372793;-0.11816067407748346;1.055251955308986;1.5560826217886794;0.1588318525718114;0.4247931092675822;0.21790016690200298];' newline ...
'cover = [-1.940559726452234;-0.27364141130466757;0.6096490191848467;0.05772237959270659;-0.00991799169367214;-0.2114018519558647;-0.01166365647510053;4.432492080111768;1.679664114999441;-0.3868757212959778;-0.4455625799447156];' newline ...
'lap = [-0.8405861024010692;-1.9463537472006074;-0.08489712734227542];' newline ...
'lapLength = 5000.0; zoneLen = 0.45; nextZone = 1.5; isLast = 0.0; tyreDelta = 0.0;' newline ...
'lapPhase = min(max(trackPos_m/lapLength,0),1);' newline ...
'p00 = logistic(zone,[1;gap_s;tyreDelta;0;0;0;zoneLen;nextZone;isLast;0]);' newline ...
'p10 = logistic(zone,[1;gap_s;tyreDelta;1;0;1;zoneLen;nextZone;isLast;gap_s]);' newline ...
'p01 = logistic(zone,[1;gap_s;tyreDelta;0;1;0;zoneLen;nextZone;isLast;0]);' newline ...
'p11 = logistic(zone,[1;gap_s;tyreDelta;1;1;0;zoneLen;nextZone;isLast;gap_s]);' newline ...
'pCover = logistic(cover,[1;2.5;0;0.5;5;gap_s;tyreDelta;zoneLen;isLast;lapPhase;0]);' newline ...
'pSuccess = (1-pCover)*p10+pCover*p11;' newline ...
'pNoDeploy = (1-pCover)*p00+pCover*p01;' newline ...
'gainUnmatched = p10-p00; gainMatched = p11-p01;' newline ...
'expectedGain = (1-pCover)*gainUnmatched+pCover*gainMatched;' newline ...
'aiRecommendation = modeEnable > 0 && expectedGain >= 0.04;' newline ...
'ruleGate = modeEnable > 0 && gap_s <= 0.90 && trackPos_m >= 1150 && trackPos_m <= 1650;' newline ...
'if ruleGate && aiRecommendation && speed_kph > 215' newline ...
'    decisionMode = 1; pRequest = 275;' newline ...
'elseif brake >= 0.22 && regenAvail > 0' newline ...
'    decisionMode = -1; pRequest = -120;' newline ...
'else' newline ...
'    decisionMode = 0; pRequest = 0;' newline ...
'end' newline ...
'end' newline ...
'function p = logistic(b,x)' newline ...
'p = min(max(1/(1+exp(-(b''*x))),0),1);' newline ...
'end'];
end

function script = regenScript()
script = [ ...
'function regenAvailable_kW = f(brake,speed_kph)' newline ...
'% Rear-axle regenerative braking availability, capped for this reference model.' newline ...
'regenAvailable_kW = min(max(brake,0)*max(speed_kph,0)*0.40,180);' newline ...
'end'];
end

function script = iceScript()
script = [ ...
'function [pICE_wheel_kW,engineTorque_Nm,fuelFlow_MJph] = f(speed_kph,throttle,brake,boost_bar)' newline ...
'rpm = min(max(speed_kph/3.6/0.330*3.20*3.50*60/(2*pi),4000),10500);' newline ...
'baseTorque = min(max(700 + 0.01*(rpm-4000),0),720);' newline ...
'effectiveThrottle = min(max(throttle*(1-brake),0),1);' newline ...
'boostFactor = min(max(0.90+0.025*boost_bar,0.90),1.05);' newline ...
'fuelFlow_MJph = min(3000,165+0.27*rpm);' newline ...
'pFuel_kW = fuelFlow_MJph*1000/3600;' newline ...
'omega = rpm*2*pi/60;' newline ...
'pShaft_kW = min(pFuel_kW*0.55*effectiveThrottle*boostFactor,baseTorque*effectiveThrottle*omega/1000*boostFactor);' newline ...
'engineTorque_Nm = max(0,pShaft_kW*1000/max(omega,1));' newline ...
'pICE_wheel_kW = max(0,pShaft_kW*0.95);' newline ...
'end'];
end

function script = turboScript()
script = [ ...
'function [boost_bar,airFlow_kgps] = f(speed_kph,throttle)' newline ...
'% Turbocharger compressor/turbine and intercooler signal-level model.' newline ...
'boost_bar = min(max(1.0+0.010*max(speed_kph,0)+2.0*max(throttle,0),1.0),5.0);' newline ...
'airFlow_kgps = min(max(0.002*max(speed_kph,0)*max(throttle,0),0),1.6);' newline ...
'end'];
end

function script = fuelScript()
script = [ ...
'function [fuelFlow_MJph,injectorDuty] = f(fuelDemand_MJph,throttle)' newline ...
'% Fuel rail, injectors and sustainable-fuel delivery monitor.' newline ...
'fuelFlow_MJph = max(fuelDemand_MJph,0);' newline ...
'injectorDuty = min(max(throttle,0),1);' newline ...
'end'];
end

function script = bmsScript()
script = [ ...
'function [pBatteryAllowed_kW,thermalState_C] = f(pBattery_kW,ePrev_MJ)' newline ...
'% Battery-management, HV interlock and thermal protection layer.' newline ...
'capacity_MJ = 14.4; eMin_MJ = 0.20*capacity_MJ; eMax_MJ = 0.95*capacity_MJ;' newline ...
'if ePrev_MJ <= eMin_MJ && pBattery_kW > 0, pBatteryAllowed_kW = 0;' newline ...
'elseif ePrev_MJ >= eMax_MJ && pBattery_kW < 0, pBatteryAllowed_kW = 0;' newline ...
'else, pBatteryAllowed_kW = min(max(pBattery_kW,-180),350); end' newline ...
'thermalState_C = 35+0.001*abs(pBatteryAllowed_kW);' newline ...
'end'];
end

function script = brakeScript()
script = [ ...
'function [brakeFraction,frictionBrakePower_kW] = f(brake,speed_kph)' newline ...
'% Brake-by-wire allocation leaves regenerative braking on the parallel path.' newline ...
'brakeFraction = min(max(brake,0),1);' newline ...
'frictionBrakePower_kW = brakeFraction*max(speed_kph,0)*18.0;' newline ...
'end'];
end

function script = governorScript()
script = [ ...
'function [pFinal_kW,clip,reason] = f(pRequest_kW,ruleGate,speed_kph,brake,ePrev_MJ)' newline ...
'cap = 350; dt = 0.25; eMin = 2.88; swing = 4.0;' newline ...
'omega = max(1,speed_kph/3.6/0.330*3.50); physical = min(cap,500*omega/1000);' newline ...
'if pRequest_kW > 0 && ruleGate > 0' newline ...
'    if speed_kph < 340, reg = 350; elseif speed_kph < 345, reg = 100*(345-speed_kph)/5; else, reg = 0; end' newline ...
'    energyLimit = max(0,(ePrev_MJ-max(eMin,ePrev_MJ-swing)))*1000/dt*0.97*0.96;' newline ...
'    pFinal_kW = min([pRequest_kW,reg,physical,350,energyLimit]); reason = 0;' newline ...
'elseif pRequest_kW < 0 && brake >= 0.22' newline ...
'    pFinal_kW = -min(abs(pRequest_kW),180); reason = 2;' newline ...
'else' newline ...
'    pFinal_kW = 0; reason = 1;' newline ...
'end' newline ...
'clip = double(abs(pFinal_kW-pRequest_kW)>1e-9);' newline ...
'end'];
end

function script = inverterScript()
script = [ ...
'function pBattery_kW = f(pMGUK_electrical_kW)' newline ...
'if pMGUK_electrical_kW >= 0, pBattery_kW = pMGUK_electrical_kW/0.97; else, pBattery_kW = pMGUK_electrical_kW*0.97; end' newline ...
'end'];
end

function script = mguScript()
script = [ ...
'function [pMechanical_kW,torque_Nm] = f(pElectrical_kW,speed_kph)' newline ...
'omega = max(1,speed_kph/3.6/0.330*3.50); eta = 0.96;' newline ...
'if pElectrical_kW >= 0, pMechanical_kW = pElectrical_kW*eta; else, pMechanical_kW = pElectrical_kW/max(eta,1e-6); end' newline ...
'torque_Nm = min(max(pMechanical_kW*1000/omega,-500),500);' newline ...
'pMechanical_kW = torque_Nm*omega/1000;' newline ...
'end'];
end

function script = batteryScript()
script = [ ...
'function [energy_MJ,soc_percent,voltage_V,current_A,pBattery_kW,temp_C] = f(pBattery_kW_in,ePrev_MJ)' newline ...
'capacity = 14.4; eMin = capacity*0.20; eMax = capacity*0.95; dt = 0.25;' newline ...
'e = min(max(ePrev_MJ-pBattery_kW_in*dt/1000,eMin),eMax); soc = min(max(e/capacity,0),1);' newline ...
'voc = 400*(0.95+0.10*soc); r = 0.08; pW = pBattery_kW_in*1000;' newline ...
'disc = max(voc^2-4*r*pW,0); current_A = (voc-sqrt(disc))/(2*r); voltage_V = max(50,voc-r*current_A);' newline ...
'current_A = pW/voltage_V; temp_C = 35+0.001*abs(pBattery_kW_in);' newline ...
'energy_MJ = e; soc_percent = 100*soc; pBattery_kW = pBattery_kW_in;' newline ...
'end'];
end

function script = gearboxScript()
script = [ ...
'function [pWheel_kW,gear,wheelTorque_Nm] = f(pICE_kW,pMGUK_kW,speed_kph)' newline ...
'gear = 1+floor(min(max((speed_kph-70)/34,0),7));' newline ...
'pWheel_kW = (pICE_kW+pMGUK_kW)*0.95;' newline ...
'wheelTorque_Nm = pWheel_kW*1000/max(speed_kph/3.6,1);' newline ...
'end'];
end

function script = aeroScript()
script = [ ...
'function drag_N = f(pWheel_kW,speed_kph)' newline ...
'% Aerodynamic drag feedback is reported as a component signal.' newline ...
'rho = 1.225; cda = 0.925; v = max(speed_kph/3.6,1);' newline ...
'drag_N = 0.5*rho*cda*v^2;' newline ...
'end'];
end

function script = vehicleScript()
script = [ ...
'function [speed_actual_kph,acceleration_m_s2,distance_m,drag_N,traction_N] = f(pWheel_kW,speed_cmd_kph,brake,gradient_rad,trackPos_m)' newline ...
'mass = 803; g = 9.81; rho = 1.225; cda = 0.925; v = max(speed_cmd_kph/3.6,1);' newline ...
'traction_N = pWheel_kW*1000/v; drag_N = 0.5*rho*cda*v^2;' newline ...
'roll_N = 0.30*mass; grade_N = mass*g*sin(gradient_rad); brake_N = min(max(brake,0),1)*18000;' newline ...
'acceleration_m_s2 = min(max((traction_N-drag_N-roll_N-grade_N-brake_N)/mass,-12),12);' newline ...
'speed_actual_kph = max(0,speed_cmd_kph+3.6*0.25*acceleration_m_s2);' newline ...
'distance_m = trackPos_m+speed_actual_kph/3.6*0.25;' newline ...
'end'];
end
